INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chahal',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chisec',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cobán',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Fray Bartolomé de las Casas',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catalina La Tinta',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Lanquín',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Panzós',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Raxruhá',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Cristóbal Verapaz',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Chamelco',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Carchá',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz Verapaz',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa María Cahabón',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Senahú',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tamahú',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tactic',1);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tucurú',1);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cubulco',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Granados',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Purulhá',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Rabinal',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Salamá',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Jerónimo',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Chicaj',2);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz el Chol',2);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Acatenango',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chimaltenango',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Tejar',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Parramos',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Patzicía',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Patzún',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pochuta',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés Itzapa',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José Poaquíl',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Comalapa',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Martín Jilotepeque',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Apolonia',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz Balanyá',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tecpán',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Yepocapa',3);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zaragoza',3);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Camotán',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chiquimula',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Concepción Las Minas',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Esquipulas',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ipala',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jocotán',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Olopa',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Quetzaltepeque',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Jacinto',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José la Arada',4);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Ermita',4);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Dolores',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Chal',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Flores',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Libertad',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Las Cruces',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Melchor de Mencos',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Poptún',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Benito',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Francisco',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Luis',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Ana',5);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sayaxché',5);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Jícaro',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Guastatoya',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Morazán',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Agustín Acasaguastlán',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio La Paz',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Cristóbal Acasaguastlán',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sanarate',6);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sansare',6);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Canillá',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chajul',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chicamán',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chiché',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chichicastenango',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chinique',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cunén',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ixcán',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Joyabaj',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nebaj',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pachalum',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Patzité',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sacapulas',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés Sajcabajá',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Ilotenango',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Bartolomé Jocotenango',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Cotzal',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Jocopilas',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz del Quiché',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Uspantán',7);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zacualpa',7);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Escuintla',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Guanagazapa',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Iztapa',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Democracia',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Gomera',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Masagua',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nueva Concepción',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Palín',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Vicente Pacaya',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Lucía Cotzumalguapa',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Siquinalá',8);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tiquisate',8);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Amatitlán',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chinautla',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chuarrancho',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ciudad de Guatemala',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Fraijanes',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Mixco',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Palencia',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José del Golfo',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José Pinula',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Sacatepéquez',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Petapa',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Ayampuc',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Sacatepéquez',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Raymundo',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catarina Pinula',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Villa Canales',9);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Villa Nueva',9);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Aguacatán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chiantla',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Colotenango',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Concepción Huista',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cuilco',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Huehuetenango',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jacaltenango',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Democracia',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Libertad',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Malacatancito',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nentón',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Huista',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Gaspar Ixchil',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Ildefonso Ixtahuacán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Atitán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Ixcoy',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Mateo Ixtatán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Acatán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Nécta',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Soloma',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Rafael La Independencia',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Rafael Pétzal',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Sebastián Coatán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Sebastián Huehuetenango',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Ana Huista',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Bárbara',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz Barillas',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Eulalia',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santiago Chimaltenango',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tectitán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Todos Santos Cuchumatán',10);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Unión Cantinil',10);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Estor',11);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Livingston',11);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Los Amates',11);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Morales',11);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Puerto Barrios',11);
