INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jalapa',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Mataquescuintla',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Monjas',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Carlos Alzatate',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Luis Jilotepeque',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Manuel Chaparrón',12);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Pinula',12);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Agua Blanca',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Asunción Mita',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Atescatempa',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Comapa',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Conguaco',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Adelanto',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Progreso',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jalpatagua',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jerez',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jutiapa',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Moyuta',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pasaco',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Quesada',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José Acatempa',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catarina Mita',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Yupiltepeque',13);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zapotitlán',13);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Almolonga',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cabricán',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cajolá',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cantel',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Coatepeque',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Colomba Costa Cuca',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Concepción Chiquirichapa',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Palmar',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Flores Costa Cuca',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Génova',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Huitán',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Esperanza',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Olintepeque',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Palestina de Los Altos',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Quetzaltenango',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Salcajá',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Carlos Sija',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Francisco La Unión',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Ostuncalco',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Martín Sacatepéquez',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Mateo',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Sigüilá',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sibilia',14);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zunil',14);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Champerico',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Asintal',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nuevo San Carlos',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Retalhuleu',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés Villa Seca',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Felipe',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Martín Zapotitlán',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Sebastián',15);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz Muluá',15);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Alotenango',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ciudad Vieja',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Jocotenango',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Antigua Guatemala',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Magdalena Milpas Altas',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pastores',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Aguas Calientes',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Bartolomé Milpas Altas',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Lucas Sacatepéquez',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Dueñas',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catarina Barahona',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Lucía Milpas Altas',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa María de Jesús',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santiago Sacatepéquez',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santo Domingo Xenacoj',16);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sumpango',16);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ayutla',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Catarina',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Comitancillo',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Concepción Tutuapa',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Quetzal',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('El Tumbador',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Esquipulas Palo Gordo',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ixchiguán',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Blanca',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Reforma',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Malacatán',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nuevo Progreso',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Ocós',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pajapita',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Río Blanco',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Sacatepéquez',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Cristóbal Cucho',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José El Rodeo',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José Ojetenam',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Lorenzo',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Marcos',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Ixtahuacán',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pablo',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro Sacatepéquez',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Rafael Pie de la Cuesta',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sibinal',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sipacapa',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tacaná',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tajumulco',17);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Tejutla',17);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Barberena',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Casillas',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chiquimulilla',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cuilapa',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Guazacapán',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nueva Santa Rosa',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Oratorio',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pueblo Nuevo Viñas',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Tecuaco',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Rafael las Flores',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz Naranjo',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa María Ixhuatán',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Rosa de Lima',18);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Taxisco',18);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Concepción',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Nahualá',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Panajachel',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés Semetabaj',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Palopó',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José Chacayá',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Lucas Tolimán',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Marcos La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pablo La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pedro La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catarina Ixtahuacán',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Catarina Palopó',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Clara La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Cruz La Laguna',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Lucía Utatlán',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa María Visitación',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santiago Atitlán',19);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Sololá',19);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Chicacao',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cuyotenango',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Mazatenango',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Patulul',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Pueblo Nuevo',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Río Bravo',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Samayac',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Antonio Suchitepéquez',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Bernardino',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Francisco Zapotitlán',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Gabriel',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José El Idolo',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San José La Maquina',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Juan Bautista',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Lorenzo',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Miguel Panán',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Pablo Jocopilas',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Bárbara',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santo Domingo Suchitepéquez',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santo Tomás La Unión',20);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zunilito',20);


INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Momostenango',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Andrés Xecul',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Bartolo',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Cristóbal Totonicapán',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Francisco El Alto',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa Lucía La Reforma',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Santa María Chiquimula',21);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Totonicapán',21);

INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Cabañas',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Estanzuela',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Gualán',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Huité',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('La Unión',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Río Hondo',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Diego',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('San Jorge',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Teculután',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Usumatlán',22);
INSERT INTO MUNICIPIO(Nombre, Departamento_idDepartamento) VALUE ('Zacapa',22);
